# Generated by Django 4.2.13 on 2026-06-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_id',
            field=models.ImageField(blank=True, help_text='Upload faculty ID card', null=True, upload_to='faculty_ids/'),
        ),
    ]
