# Generated by Django 4.2.13 on 2026-06-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0004_siteassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NarrativeReport',
        ),
    ]
