# Generated by Django 4.2.13 on 2026-06-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
        ('coordinator', '0006_remove_siteassignment_site_location_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='core.course'),
        ),
    ]
