# Generated by Django 4.2.13 on 2026-06-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0007_alter_site_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ojtprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
