# Generated by Django 4.2.13 on 2026-06-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0008_alter_ojtprogram_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ojtprogram',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ojtprogram',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
