# Generated by Django 4.2.13 on 2026-07-02 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinator', '0009_alter_ojtapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
