# Generated by Django 4.2.13 on 2026-07-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0010_site_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='contact_person',
            new_name='supervisor_name',
        ),
    ]
