# Generated by Django 4.2.13 on 2026-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0011_rename_site_contact_person_to_supervisor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ojtapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
