# Generated by Django 4.2.13 on 2026-07-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0013_attendance_auto_clocked_out_attendance_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtapplication',
            name='preferred_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='coordinator.site'),
        ),
    ]
