# Generated by Django 4.2.30 on 2026-07-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0014_ojtapplication_preferred_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
