# Generated by Django 4.2.30 on 2026-08-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0015_site_address_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='gmail',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
