# Generated by Django 4.2.30 on 2026-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0016_add_gmail_to_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contact_persons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
