# Generated by Django 4.2.30 on 2026-08-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0017_add_contact_persons_to_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_in_am',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_in_pm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out_am',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_out_pm',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
