# Generated by Django 4.2.13 on 2026-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0020_temporaryleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtapplication',
            name='insurance',
            field=models.FileField(blank=True, null=True, upload_to='insurance/'),
        ),
        migrations.AddField(
            model_name='ojtapplication',
            name='moa',
            field=models.FileField(blank=True, null=True, upload_to='moa/'),
        ),
        migrations.AddField(
            model_name='ojtapplication',
            name='reply_form',
            field=models.FileField(blank=True, null=True, upload_to='reply_forms/'),
        ),
        migrations.AddField(
            model_name='ojtapplication',
            name='waiver_consent',
            field=models.FileField(blank=True, null=True, upload_to='waivers/'),
        ),
    ]
