# Generated by Django 4.2.13 on 2026-06-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinator', '0003_narrativereport'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNarrativeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='narratives/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='narratives/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='narratives/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='narratives/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_narratives', to='coordinator.ojtprogram')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_narrative_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Narrative Report',
                'verbose_name_plural': 'Student Narrative Reports',
                'ordering': ['-log_date'],
                'unique_together': {('student', 'log_date')},
            },
        ),
    ]
