# Generated by Django 4.2.13 on 2026-06-20 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_studentnarrativereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnarrativereport',
            name='feedback',
            field=models.TextField(blank=True, help_text='Coordinator feedback on the report'),
        ),
        migrations.AddField(
            model_name='studentnarrativereport',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Coordinator grade (1-100)', null=True),
        ),
        migrations.AddField(
            model_name='studentnarrativereport',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentnarrativereport',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_narratives', to=settings.AUTH_USER_MODEL),
        ),
    ]
