# Generated by Django 4.2.30 on 2026-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_facialrecognition_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facialrecognition',
            name='consent_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consent was recorded', null=True),
        ),
        migrations.AddField(
            model_name='facialrecognition',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether the student explicitly consented to facial data collection'),
        ),
        migrations.AddField(
            model_name='facialrecognition',
            name='liveness_confirmed',
            field=models.BooleanField(default=False, help_text='Whether a liveness check passed at enrollment time'),
        ),
        migrations.AddField(
            model_name='facialrecognition',
            name='quality_score',
            field=models.FloatField(default=0.0, help_text='Composite face image quality score (0-100) at enrollment time'),
        ),
    ]
