# Generated by Django 4.2.13 on 2026-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='activity_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('program_created', 'Program Created'), ('approval_made', 'Approval Made'), ('report_generated', 'Report Generated'), ('program_deleted', 'Program Deleted')], max_length=50),
        ),
    ]
