# Generated by Django 4.2.30 on 2026-09-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_systemlog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='activity_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_archived', 'User Archived'), ('user_restored', 'User Restored'), ('program_created', 'Program Created'), ('program_deleted', 'Program Deleted'), ('program_archived', 'Program Archived'), ('program_restored', 'Program Restored'), ('approval_made', 'Approval Made'), ('report_generated', 'Report Generated')], max_length=50),
        ),
    ]
