# Generated by Django 4.2.13 on 2026-06-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
